### PR TITLE
Updated project description and added usage example to readme

### PR DESCRIPTION
**Pull request by MaxvandenBoom**
Hi Jan,

Since I have PyMef as a dependency in my own project I thought would make some modest tweaks to the presentation  :)
Three small updates:
- I added some project information to the pyproject.toml (adapted from your readme). This way the https://pypi.org/project/pymef/ page would look a bit more filled out (it's project description is empty now) on the next release. 
- I've added a small usage example to the readme, to show how little is needed for use.
- One link in the readme was broken (or only accessable from Mayo perhaps?)

Hope you feel these updates are an improvement as well

### CODE REVIEW

**Comment by MaxvandenBoom** [comment]
Hmm, the tests are failing because I (deliberately) left out the `['version']` tag from the `pyproject.toml`. I was hoping it would work without that tag.

Normally I would have pyproject pull it automatically from the code, but I did not find it being tracked there.
How do you go about versioning the releases in your builds?

**Comment by cimbi** [comment]
the version is in setup.py but I am happy to move it to project.toml

**Comment by MaxvandenBoom** [comment]
I can do that for you in this pull request if you want. This way you can merge it including the example I added to the readme.

**Comment by cimbi** [comment]
yes, please do. should the args be removed from setup.py then?

**Comment by MaxvandenBoom** [comment]
From what I understand the best solution is to have the version in a separate file, like this:
https://github.com/MultimodalNeuroimagingLab/ieegprep/blob/master/ieegprep/version.py

In `__init__.py` I would add:
`from pymef.version import __version__`

Then in the setup.py file you can have:
```
from pymef import __version__
setup(
    name = 'pymef',
    version = __version__,
    ...
    )
```

and in pyproject.toml you can do:
```
[tool.setuptools.dynamic]
version = {attr = "pymef.version.__version__"}
```

I'll update this pull request so you can see

**Comment by MaxvandenBoom** [comment]
Ready to go/merge!

The versioning is only tracked in /pymef/version.py
I currently left it at 1.4.1

I removed the duplicate fields from setup.py, these are already defined in pyproject.toml.
According to PEP 517, PEP 518 and PEP 621, pyproject.toml is the standard for these fields, with setup.py for (compiling) extras that are not yet implemented in the pyproject.toml structure.

**Pull request merged**
